ALTER TABLE applications
    MODIFY COLUMN status ENUM('PENDING', 'REVIEWED', 'REVIEWING', 'ACCEPTED', 'REJECTED') NOT NULL;

UPDATE applications SET status ='REVIEWING' WHERE status = 'REVIEWED';

ALTER TABLE applications
    MODIFY COLUMN status ENUM('PENDING', 'REVIEWING', 'ACCEPTED', 'REJECTED') NOT NULL;